### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gouthamve** [mjibson/mog#16]
I think this would be useful for people who would like to contribute:

- [ ] Google Music radio
- [ ] Google Music and soundcloud playlists
- [ ] Youtube (needs vorbis or AAC decoder)
- [ ] Ogg Vorbis (**WIP**: https://github.com/mjibson/vorbis)
- [ ] SPC (Super Nintendo) decoding (**WIP**: https://github.com/mjibson/spc/tree/gme)
- [ ] Album and Artist list in the UI
- [ ] API docs (useful for building clients and integrations)

Future implementations:
- [ ] Spotify
- [ ] AAC (iTunes, Apple music format)

**Comment by svnpenn** [comment]
https://github.com/mjibson/moggio/issues/48
